### ISSUE TITLE
Platform fails to load: cannot import name 'make_template_entity_base_schema' from 'homeassistant.components.template.schemas'

### ISSUE THREAD

**Issue by arnav89** [jcwillox/hass-template-climate#151]
### The problem

After updating Home Assistant Core, the `climate_template` platform fails to load with the following error:
Platform error ‘climate’ from integration ‘climate_template’ - cannot import name
‘make_template_entity_base_schema’ from ‘homeassistant.components.template.schemas’
(/usr/src/homeassistant/homeassistant/components/template/schemas.py)
This appears to be caused by a breaking change to HA core's internal 
`homeassistant.components.template.schemas` module, which this integration imports 
from directly. The function `make_template_entity_base_schema` either no longer 
exists at that path or has been renamed/moved in this core release.

The configuration itself was working correctly prior to the core update and has not 
been changed.
## What I expected to happen

The `climate_template` platform should load normally and the configured climate 
entity should be created, as it was before the core update.

## What actually happened

The platform fails to load entirely. Home Assistant logs the import error above and 
the climate entity does not get created. Other entities in the same config (scripts, 
switches, template fan) are unaffected since they don't depend on this import path.
## Steps to reproduce

1. Have a working `climate_template` config (example below)
2. Update Home Assistant Core to 2026.9.0
3. Restart
4. Check Settings → Tools → Check YAML Configuration — the import error appears
5. The climate entity is absent from Settings → Devices & Services → Entities

### What version of Template Climate has the issue?

1.4.0

### What version of Home Assistant are you running?

2026.9.0

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml
climate:
  - platform: climate_template
    name: "Bedroom AC"
    unique_id: bedroom_ac
    modes:
      - "off"
      - cool
      - dry
      - fan_only
    fan_modes:
      - auto
      - low
      - mid
      - max
    min_temp: 16
    max_temp: 30
    precision: 1
    temp_step: 1
    current_temperature_template: "{{ states('sensor.bedroom_monitor_temperature') }}"
    set_temperature:
      - service: script.turn_on
        target: {entity_id: script.ac_send_command}
        data:
          variables:
            command: "temperature"
            value: "{{ temperature | int }}"
```

### Anything in the logs that might be useful for us?

```python3

```

**Comment by peterdelios** [comment]
HA 2026.9 compatibility issue with Template Climate v1.4.0

After upgrading Home Assistant to 2026.9, Template Climate v1.4.0 failed to load.

The Home Assistant log reported:

Platform error: climate - cannot import name 'make_template_entity_base_schema' from 'homeassistant.components.template.schemas'

The traceback identified the problem at:

/config/custom_components/climate_template/climate.py, line 53

The original line was:

Line 53:
from homeassistant.components.template.schemas import make_template_entity_base_schema

Home Assistant 2026.9 no longer provides make_template_entity_base_schema from homeassistant.components.template.schemas.

Fix applied to climate.py:

1. Removed the import at line 53:

Line 53:
from homeassistant.components.template.schemas import make_template_entity_base_schema

2. Added a local replacement function after:

Line 117:
DEFAULT_NAME = "Template Climate"

The replacement function was added at approximately lines 120-132:

Lines 120-132:
def make_template_entity_base_schema(domain: str, default_name: str) -> vol.Schema:
    """Return a schema with default name."""
    return vol.Schema(
        {
            vol.Optional(CONF_DEFAULT_ENTITY_ID): vol.All(
                cv.entity_id, cv.entity_domain(domain)
            ),
            vol.Optional(CONF_ICON): cv.template,
            vol.Optional(CONF_NAME, default=default_name): cv.template,
            vol.Optional(CONF_PICTURE): cv.template,
            vol.Optional(CONF_UNIQUE_ID): cv.string,
        }
    )

3. Added CONF_UNIQUE_ID to the existing import from homeassistant.const.

The import section now includes:

Lines 48-54:
CONF_NAME,
CONF_STATE,
CONF_UNIQUE_ID,
CONF_VALUE_TEMPLATE,

4. The existing PLATFORM_SCHEMA code was left unchanged.

Lines 139-140:

PLATFORM_SCHEMA = cv.PLATFORM_SCHEMA.extend(
    make_template_entity_base_schema(CLIMATE_DOMAIN, DEFAULT_NAME).schema
).extend(

No other Template Climate functionality or configuration was changed.

After applying the changes:

- Home Assistant configuration validation passed.
- Home Assistant restarted successfully.
- Template Climate loaded successfully.
- The climate entity returned and is functioning normally again on Home Assistant 2026.9.

This appears to be a compatibility issue caused by Home Assistant 2026.9 removing make_template_entity_base_schema from homeassistant.components.template.schemas, while Template Climate v1.4.0 still imports it from that location.

Template Climate v1.4.0 therefore requires an update to remain compatible with Home Assistant 2026.9.

**Comment by tureka** [comment]
Same issue here.

**Comment by ndrinta** [comment]
Detected blocking call to import_module causing event loop instability in HA 2026.9.0

```Logger: homeassistant.util.loop
Source: util/loop.py:75

Detected blocking call to import_module with args ('custom_components.climate_template.climate',) in /usr/src/homeassistant/homeassistant/loader.py, line 1325: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. 

Traceback (most recent call last): 
File "<frozen runpy>", line 203, in _run_module_as_main 
File "<frozen runpy>", line 88, in _run_code 
File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) 
...
File "/usr/src/homeassistant/homeassistant/loader.py", line 1325, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")```

**Comment by lebdim** [comment]
Same failure here on Home Assistant **2026.9.0** (HAOS, qemux86-64) with `climate_template` v1.4.0 — the platform fails to import, so the templated climate entity ends up `restored: true` / `unavailable`.

Root cause is home-assistant/core#178762 (merged 2026-08-13), which collapsed `make_template_entity_base_schema`, `make_template_entity_common_modern_schema` and `make_template_entity_common_modern_attributes_schema` into a single `make_template_entity_common_schema(domain, default_name, blocked_attributes=None)` and dropped the `*_LEGACY` schema constants.

#154 has a backward-compatible fix (try the new name, fall back to the old one), which I verified on a live 2026.9.0 install — the platform loads cleanly afterwards. A merge there would close this.
