### ISSUE TITLE
Beta 2025.08.0b0 breaks this integration

### ISSUE THREAD

**Issue by EDelsman** [jcwillox/hass-template-climate#109]
### The problem

The upcoming releasr 2025.8.0 has changes to templates that break this integration. It reports an error on the log about the availability template. However, removing that from the configutation does not change a thing.

### What version of Template Climate has the issue?

1.0.1

### What version of Home Assistant are you running?

2025.08.0b0

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml

```

### Anything in the logs that might be useful for us?

```python3
Logger: homeassistant.components.climate
Bron: helpers/entity_platform.py:451
integratie: Klimaat (documentatie, problemen)
Eerst voorgekomen: 18:25:59 (7 gebeurtenissen)
Laatst gelogd: 18:25:59

Error while setting up climate_template platform for climate: TemplateEntity.__init__() got an unexpected keyword argument 'availability_template'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/climate_template/climate.py", line 176, in async_setup_platform
    async_add_entities([TemplateClimate(hass, config)])
                        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/climate_template/climate.py", line 187, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        hass,
        ^^^^^
    ...<3 lines>...
        unique_id=config.get(CONF_UNIQUE_ID, None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: TemplateEntity.__init__() got an unexpected keyword argument 'availability_template'
```

**Comment by Tamas-Toth-ebola** [comment]
I can confirm the same... Will try to comment out the `availability_template`, let's see what happens...

**Comment by Tamas-Toth-ebola** [comment]
The result is the same, which is interesting as in this case I explicitly do not send that attribute, so there should be something else in the `climate.py`...

**Comment by Tamas-Toth-ebola** [comment]
Meanwhile I realized, what is the real problem, as Home Assistant already does not support the `availability_template`, so it should be changed to another solution...

Ok, for now I have to let it go 😕

**Comment by jcwillox** [comment]
Looks like it was broken by https://github.com/home-assistant/core/pull/147504, but the fix looks quite straightfoward we just need to pass in the whole config object now instead of using kwargs.

**Comment by Petro31** [comment]
> Looks like it was broken by [home-assistant/core#147504](https://github.com/home-assistant/core/pull/147504), but the fix looks quite straightfoward we just need to pass in the whole config object now instead of using kwargs.

Yes, see this comment https://github.com/jcwillox/hass-template-climate/pull/110#discussion_r2245186710

**Comment by Petro31** [comment]
> Looks like it was broken by [home-assistant/core#147504](https://github.com/home-assistant/core/pull/147504), but the fix looks quite straightfoward we just need to pass in the whole config object now instead of using kwargs.

The whole change that should work after you add a few imports...

```
from homeassistant.components.climate import DOMAIN as CLIMATE_DOMAIN
from homeassistant.components.template.helpers import async_setup_template_platform
```

... Also add imports for annotation AddEntitiesCallback and DiscoveryInfoType 

```
async def async_setup_platform(
    hass: HomeAssistant,
    config: ConfigType,
    async_add_entities: AddEntitiesCallback,
    discovery_info: DiscoveryInfoType | None = None,
) -> None:
    """Set up the template number."""
    await async_setup_template_platform(
        hass,
        CLIMATE_DOMAIN,
        config,
        TemplateClimate,
        None,
        async_add_entities,
        discovery_info,
    )

class TemplateClimate(TemplateEntity, ClimateEntity, RestoreEntity):
    """A template climate component."""

    _attr_should_poll = False
    _enable_turn_on_off_backwards_compatibility = False

    def __init__(self, hass: HomeAssistant, config: ConfigType, unique_id: str | None):
        """Initialize the climate device."""
        super().__init__(hass, config, unique_id)

        # set attrs
        self._attr_min_temp = config[CONF_TEMP_MIN]
        self._attr_max_temp = config[CONF_TEMP_MAX]
        ... all the remaining code after the line above this...
```

**Comment by Petro31** [comment]
> Perfect thanks! I just made the change to support this, but then noticed the keys changed so I couldn't just pass in config, and this is much better than what I had in mind.

Yeah, so the `async_setup_template_platform` handles all sorts of key translations to make the `_template` things map to the non `_template` things.  So all you need to do is pass the instantiation through that function by matching the constructor.  My goal in all the template changes is to provide a similar set of base options that all template entities have inherently.

**Comment by Tamas-Toth-ebola** [comment]
I can also confirm, that with the new beta, everything work again! 

Thanks for this very fast responsive to the problem!

**Comment by jcwillox** [comment]
Release is out now!

Thanks for the heads up on the issue, as I wouldn't have checked the beta otherwise, and been able to fix it before the actual release.
