### ISSUE TITLE
Fallo actualización Home assistant core 2026.9.0b0

### ISSUE THREAD

**Issue by pilma73** [jcwillox/hass-template-climate#149]
### The problem

he actualizado esta versión beta y me ha dejado de funcionar los componentes que tenia creados con esta integración.

en el log me daba este fallo.

Registrador: homeassistant.util.loop

Fuente: util/loop.py:75

Ocurrió por primera vez: 11:17:15 (1 ocurrencia)

Última vez registrado: 11:17:15

Detected blocking call to import_module with args ('custom_components.climate_template.climate',) in /usr/src/homeassistant/homeassistant/loader.py, line 1325: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 203, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 280, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2056, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config.py", line 1079, in _async_load_and_validate_platform_integration platform = await p_integration.integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1128, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1194, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1118, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1293, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1325, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}") 

### What type of installation are you running?

None

### Example YAML snippet

```yml

```

### Anything in the logs that might be useful for us?

```python3

```

**Comment by pilma73** [comment]
Se me olvido decir que estoy usando la ultima versión de la integración la v1.4.0

he tenido que desinstalar la versión beta para poder funcionar

**Comment by Tamas-Toth-ebola** [comment]
I can confirm this problem from my side also.

**Comment by BradleyFord** [comment]
I am also getting this error

`Logger: homeassistant.config
Source: config.py:1079
First occurred: 9:24:37 PM (11 occurrences)
Last logged: 9:24:38 PM

Platform error: climate - cannot import name 'make_template_entity_base_schema' from 'homeassistant.components.template.schemas' (/usr/src/homeassistant/homeassistant/components/template/schemas.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1079, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1128, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1224, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name 'make_template_entity_base_schema' from 'homeassistant.components.template.schemas' (/usr/src/homeassistant/homeassistant/components/template/schemas.py)`

**Comment by dcapslock** [comment]
The fix is straightforward being a schema change where two were merged. So `make_template_entity_base_schema` is no longer available and `make_template_entity_common_schema` needs to be used which is fine as the two extra parameters have defaults and not needed by template climate.

I have tested my own fix to try and import `make_template_entity_common_schema` (2026.9.0(b0)) and if that fails, load `make_template_entity_base_schema` as `make_template_entity_common_schema`.

See https://github.com/jcwillox/hass-template-climate/commit/9a45b99372d9b0734cc7514ca5ff85415cbb7452. Make these changes and you are good to go. I am not sure how @jcwillox may wish to fix, or to be backward compatible or not, which my fix is, so not submitting a PR at this stage.

**Comment by pilma73** [comment]
hola he realizado el cambio propuesto por @dcapslock y a mi me funciona.

Muchas gracias

**Comment by LikeToAccess** [comment]
I concur that @dcapslock fix resolved this issue. The change to cimate.py is working on 2026.9.0b4. Thank you so much for this resolution!

**Comment by Lamarqe** [comment]
I created a PR: https://github.com/jcwillox/hass-template-climate/pull/150

**Comment by davidlang42** [comment]
I'm also getting this issue, but I don't understand @dcapslock 's issue with fixing it- HA core made a change to the API, so the integration needs to be kept up to date with that. If someone is locked on an old version of HA core for some specific reason, then they are locked on the old version of this integration also. There is no reason I can see to stop this integration from working with the current version of HA, and have approved the PR as such.

@jcwillox as code-owner, would you be able to merge the PR when you get a chance?

**Comment by Tamas-Toth-ebola** [comment]
> I'm also getting this issue, but I don't understand [@dcapslock](https://github.com/dcapslock) 's issue with fixing it- HA core made a change to the API, so the integration needs to be kept up to date with that. If someone is locked on an old version of HA core for some specific reason, then they are locked on the old version of this integration also. There is no reason I can see to stop this integration from working with the current version of HA, and have approved the PR as such.
> 
> [@jcwillox](https://github.com/jcwillox) as code-owner, would you be able to merge the PR when you get a chance?

It is already done now 😄

@jcwillox thanks for the update!
